import { useMemo, useState } from 'react';
import PageHeader from '../../components/PageHeader.jsx';
import Button from '../../components/Button.jsx';
import DataTable from '../../components/DataTable.jsx';
import { Badge } from '../../components/Badge.jsx';
import Modal from '../../components/Modal.jsx';
import { FormField, Select } from '../../components/FormField.jsx';
import { REPORTS as INITIAL_REPORTS, PLAYERS } from '../../data/mockData.js';
import { formatDate } from '../../utils/format.js';
import { useToast } from '../../context/ToastContext.jsx';

const TYPE_TONE = { Player: 'primary', Training: 'info', Tournament: 'cyan', Performance: 'warn', Development: 'amber' };

export default function CoachReports() {
  const [reports, setReports] = useState(INITIAL_REPORTS);
  const [genOpen, setGenOpen] = useState(false);
  const [reportType, setReportType] = useState('Player');
  const [subject, setSubject] = useState(PLAYERS[0].name);
  const { showToast } = useToast();

  const generate = () => {
    setReports((list) => [
      { id: `RPT${String(list.length + 1).padStart(3, '0')}`, type: reportType, subject, generatedBy: 'Ravi Jayasinghe', date: new Date().toISOString().slice(0, 10), format: 'PDF', status: 'Ready' },
      ...list,
    ]);
    showToast('Report generated (demo only — real generation arrives in a later phase).');
    setGenOpen(false);
  };

  const visible = useMemo(() => reports, [reports]);

  return (
    <>
      <PageHeader
        title="Reports"
        subtitle="Player, Training, Performance and Development reports for your squad"
        actions={<Button icon="description" onClick={() => setGenOpen(true)}>Generate Report</Button>}
      />

      <DataTable
        rows={visible}
        emptyTitle="No reports yet"
        columns={[
          { key: 'type', header: 'Type', render: (r) => <Badge tone={TYPE_TONE[r.type]}>{r.type}</Badge> },
          { key: 'subject', header: 'Subject' },
          { key: 'generatedBy', header: 'Generated By' },
          { key: 'date', header: 'Date', render: (r) => formatDate(r.date) },
          { key: 'format', header: 'Format', render: (r) => <span className="mono">{r.format}</span> },
          { key: 'actions', header: '', render: () => <Button size="sm" variant="secondary" icon="download" onClick={() => showToast('Report download will be wired up in a later phase.')}>Download</Button> },
        ]}
      />

      <Modal
        open={genOpen}
        onClose={() => setGenOpen(false)}
        title="Generate Report"
        footer={<>
          <Button variant="secondary" onClick={() => setGenOpen(false)}>Cancel</Button>
          <Button variant="primary" icon="description" onClick={generate}>Generate</Button>
        </>}
      >
        <div className="form-grid">
          <FormField label="Report Type">
            <Select value={reportType} onChange={(e) => { setReportType(e.target.value); setSubject(PLAYERS[0].name); }}>
              <option>Player</option>
              <option>Training</option>
              <option>Performance</option>
              <option>Development</option>
            </Select>
          </FormField>
          <FormField label="Player">
            <Select value={subject} onChange={(e) => setSubject(e.target.value)}>
              {PLAYERS.map((p) => <option key={p.id}>{p.name}</option>)}
            </Select>
          </FormField>
        </div>
      </Modal>
    </>
  );
}
