import { useMemo, useState } from 'react';
import PageHeader from '../../components/PageHeader.jsx';
import { Card } from '../../components/Card.jsx';
import Button from '../../components/Button.jsx';
import DataTable from '../../components/DataTable.jsx';
import { Badge } from '../../components/Badge.jsx';
import Modal from '../../components/Modal.jsx';
import { FormField, Select } from '../../components/FormField.jsx';
import { REPORTS as INITIAL_REPORTS, PLAYERS, TOURNAMENTS } from '../../data/mockData.js';
import { formatDate } from '../../utils/format.js';
import { useToast } from '../../context/ToastContext.jsx';

const TYPE_TONE = { Player: 'primary', Training: 'info', Tournament: 'cyan', Performance: 'warn', Development: 'amber' };

export default function Reports() {
  const [reports, setReports] = useState(INITIAL_REPORTS);
  const [typeFilter, setTypeFilter] = useState('All');
  const [genOpen, setGenOpen] = useState(false);
  const { showToast } = useToast();

  const [reportType, setReportType] = useState('Player');
  const [subject, setSubject] = useState(PLAYERS[0].name);
  const [format, setFormat] = useState('PDF');

  const filtered = useMemo(
    () => reports.filter((r) => typeFilter === 'All' || r.type === typeFilter),
    [reports, typeFilter],
  );

  const subjectOptions = reportType === 'Tournament' ? TOURNAMENTS.map((t) => t.name) : PLAYERS.map((p) => p.name);

  const generate = () => {
    setReports((list) => [
      { id: `RPT${String(list.length + 1).padStart(3, '0')}`, type: reportType, subject, generatedBy: 'Admin User', date: new Date().toISOString().slice(0, 10), format, status: 'Ready' },
      ...list,
    ]);
    showToast('Report generated (demo only — no file is actually produced until Phase 8).');
    setGenOpen(false);
  };

  return (
    <div className="admin-legacy">
      <Card className="legacy-page-card">
        <PageHeader
          title="Reports"
          subtitle="Player, Training, Tournament, Performance and Development reports in one place"
          actions={<Button icon="description" onClick={() => setGenOpen(true)}>Generate Report</Button>}
        />

        <div className="table-toolbar">
          <div className="filter-row">
            {['All', 'Player', 'Training', 'Tournament', 'Performance', 'Development'].map((t) => (
              <Button key={t} size="sm" variant={typeFilter === t ? 'primary' : 'secondary'} onClick={() => setTypeFilter(t)}>{t}</Button>
            ))}
          </div>
        </div>

        <DataTable
          rows={filtered}
          emptyTitle="No reports yet"
          columns={[
            { key: 'type', header: 'Type', render: (r) => <Badge tone={TYPE_TONE[r.type]}>{r.type}</Badge> },
            { key: 'subject', header: 'Subject' },
            { key: 'generatedBy', header: 'Generated By' },
            { key: 'date', header: 'Date', render: (r) => formatDate(r.date) },
            { key: 'format', header: 'Format', render: (r) => <span className="mono">{r.format}</span> },
            {
              key: 'actions', header: '',
              render: () => <Button size="sm" variant="secondary" icon="download" onClick={() => showToast('Report download will be wired up once real report generation exists (later phase).')}>Download</Button>,
            },
          ]}
        />
      </Card>

      <Modal
        open={genOpen}
        onClose={() => setGenOpen(false)}
        title="Generate Report"
        subtitle="Player, Training, Tournament, Performance and Development report types (FR18)"
        footer={<>
          <Button variant="secondary" onClick={() => setGenOpen(false)}>Cancel</Button>
          <Button variant="primary" icon="description" onClick={generate}>Generate</Button>
        </>}
      >
        <div className="form-grid">
          <FormField label="Report Type">
            <Select value={reportType} onChange={(e) => { setReportType(e.target.value); setSubject(e.target.value === 'Tournament' ? TOURNAMENTS[0].name : PLAYERS[0].name); }}>
              <option>Player</option>
              <option>Training</option>
              <option>Tournament</option>
              <option>Performance</option>
              <option>Development</option>
            </Select>
          </FormField>
          <FormField label="Subject">
            <Select value={subject} onChange={(e) => setSubject(e.target.value)}>
              {subjectOptions.map((s) => <option key={s}>{s}</option>)}
            </Select>
          </FormField>
          <FormField label="Format">
            <Select value={format} onChange={(e) => setFormat(e.target.value)}>
              <option>PDF</option>
              <option>Excel</option>
            </Select>
          </FormField>
        </div>
        <p className="text-faint" style={{ fontSize: 11.5, marginTop: 4, marginBottom: 0 }}>
          This creates a demo row only. Real report generation (PDF/Excel export) is built in a later phase.
        </p>
      </Modal>
    </div>
  );
}
